### ISSUE TITLE
Sugestão: Implementar download de imagens de eanpictures.com.br

### ISSUE THREAD

**Issue by claytonaalves** [tiagopassarelladt/DTImagem#1]
E aí @tiagopassarelladt, não sei se vc conhece mas existe também o http://eanpictures.com.br/.

**Comment by tiagopassarelladt** [comment]
> E aí @tiagopassarelladt, não sei se vc conhece mas existe também o http://eanpictures.com.br/.

Desnecessário colocar eanpictures uma vez que esse componente nao depende de API nem de servidor para obter imagens o que já é um grande diferencial, colocar dependência de uma API seria andar para traz

**Comment by claytonaalves** [comment]
> nao depende de API nem de servidor

Não depende de servidor ?

Tive a impressão de que o componente fazia uso de serviços como o cosmos da bluesoft...

```pascal
retorno := URLDownloadToFile(nil, PChar('https://cdn-cosmos.bluesoft.com.br/products/'+ Codigo), PChar(FCaminhoImagem), 0, nil);
```
... e a pesquisa de imagens do google.

```pascal
Response  := IdHTTP1.Get('https://www.google.com/search?q='+ Pesquisa +'&tbm=isch');
```

mas blz... bora andar pra frente.

**Comment by tiagopassarelladt** [comment]
> > nao depende de API nem de servidor
> 
> 
> 
> Não depende de servidor ?
> 
> 
> 
> Tive a impressão de que o componente fazia uso de serviços como o cosmos da bluesoft...
> 
> 
> 
> ```pascal
> 
> retorno := URLDownloadToFile(nil, PChar('https://cdn-cosmos.bluesoft.com.br/products/'+ Codigo), PChar(FCaminhoImagem), 0, nil);
> 
> ```
> 
> ... e a pesquisa de imagens do google.
> 
> 
> 
> ```pascal
> 
> Response  := IdHTTP1.Get('https://www.google.com/search?q='+ Pesquisa +'&tbm=isch');
> 
> ```
> 
> 
> 
> mas blz... bora andar pra frente.

Nao depende amigo, se voce olhar o componente a cosmos é uma opção apenas que por default vai desabilitada. O componente nao depende de nenhuma API se voce assistir a video aula com voce nao assistiu você entenderá o que estou dizendo, agora caso deseje um componente de imagens para eanpictures ou outras APIs este nao é o componente que vai te atender
